### ISSUE TITLE
Floor layout prototype

### ISSUE THREAD

**Issue by John-Ingram** [CS499-RoboVac/Robovac#16]

**Comment by John-Ingram** [comment]
![Image](https://github.com/CS499-RoboVac/Robovac/assets/26239423/fd93e3ae-b921-413c-9da3-4eddd0ff1d99)

**Comment by Brenneman-SBO** [comment]
- **Map** is a Dict of type `(int, int) : FloorTile`
- `FloorTile` is a Class with members:

  - dirtiness (float)

 - carpet type (Enum)
 - room name (String) *(possibly int)*
 - method `void Clean(float efficiency)`
- if index not in dict keys, tile is impassable
